language: python
python:
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - graphviz

notifications:
  email: false

install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install graphviz; fi
  - python -m pip install coveralls codecov
  - python -m pip install -e .

script:
  - python setup.py test

after_success:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then coveralls; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then codecov; fi
