language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
        - os: osx
          language: generic

addons:
  apt:
    packages:
      - graphviz

notifications:
  email: false

install:
  - python -m pip install pytest pytest-cov
  - python -m pip install coveralls
  - python -m pip install codecov
  - python setup.py install

script:
  - py.test --cov=phylosofs --cov-report term-missing

after_success:
  - coveralls
  - codecov
