language: python

os:
  - linux
  - osx

python:
  - 2.7

notifications:
  email: false

install:
  - pip install pytest pytest-cov coveralls
  - python setup.py install

script:
  - py.test --cov --cov-report term-missing
