language: python

os:
  - linux

addons:
  apt:
    packages:
      - graphviz

python:
  - 2.7

notifications:
  email: false

install:
  # - pip install pytest pytest-cov coveralls
  - pip install coverage
  - python setup.py install

script:
  - coverage run test/test_phylosofs.py
  # - py.test --cov=phylosofs --cov-report term-missing
