language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
        - os: osx
          language: generic

addons:
  apt:
    packages:
      - graphviz

notifications:
  email: false

install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then; brew install python; fi
  - pip install pytest pytest-cov
  - pip install coveralls
  # - pip install coverage
  - pip install codecov
  - python setup.py install

script:
  # - coverage run test/test_phylosofs.py
  - py.test --cov=phylosofs --cov-report term-missing

after_success:
  - coveralls
  - codecov
