language: python

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - graphviz

python:
  - 2.7

notifications:
  email: false

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      brew install python
    fi

install:
  - pip install pytest pytest-cov coveralls
  - python setup.py install

script:
  - py.test --cov --cov-report term-missing
