language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
        - os: osx
          sudo: required
          language: generic

addons:
  apt:
    packages:
      - graphviz

notifications:
  email: false

install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install graphviz; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then curl -O https://bootstrap.pypa.io/get-pip.py; sudo python get-pip.py --no-setuptools --no-wheel --ignore-installed; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python -m pip install pytest pytest-cov coveralls codecov --user --ignore-installed; else python -m pip install pytest pytest-cov coveralls codecov; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python -m pip install . --user --ignore-installed; else python setup.py install; fi

script:
  - python -m pytest --cov=phylosofs --cov-report term-missing

after_success:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then coveralls; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then codecov; fi
