build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # - cinst graphviz
  - choco install pip
  - choco install graphviz
  # - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  # - conda config --set always_yes yes --set changeps1 no
  # - conda update -q conda
  # - conda info -a
  # - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
  # - activate test-environment
  - pip install pytest
  - pip install .

test_script:
  - py.test
