build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - choco install graphviz
  - pip install pytest
  - pip install .

test_script:
  - py.test --doctest-modules
