# https://github.com/coala/coala-quickstart/blob/master/.ci/appveyor.yml
environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install --upgrade setuptools pip"
  - "choco install graphviz"
  - "python -m pip install numpy" # is needed to install scikit-bio
  - "python -m pip install -e ."

build: false

test_script:
  - "python setup.py test "
