build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # - cinst graphviz
  - choco install graphviz
  - subst Q: "C:\\Program Files (x86)\\Graphviz2.38"
  # - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  # - conda config --set always_yes yes --set changeps1 no
  # - conda update -q conda
  # - conda info -a
  # - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
  # - activate test-environment
  ## - git clone https://github.com/pygraphviz/pygraphviz.git
  ## - cd pygraphviz
  ## - python setup.py install --include-path="C:\graphviz\Graphviz2.38\include" --library-path="C:\graphviz\Graphviz2.38\lib\release\lib"
  ## - cd ..
  # - pip install pygraphviz --include-path="C:\graphviz\Graphviz2.38\include" --library-path="C:\graphviz\Graphviz2.38\lib\release\lib"
  ##- pip install --global-option=build_ext --global-option="-IQ:\include" --global-option="-LQ:\lib\release\lib" pygraphviz
  - pip install pygraphviz --include-path="Q:\include" --library-path="Q:\lib\release\lib"
  - pip install pytest
  - pip install .

test_script:
  - py.test
