echo "                                                                             "
echo "          _____   _             _         _____          __   _____          "
echo "         |  __ \ | |           | |       / ____|        / _| / ____|         "
echo "         | |__) || |__   _   _ | |  ___ | (___    ___  | |_ | (___           "
echo "         |  ___/ | '_ \ | | | || | / _ \ \___ \  / _ \ |  _| \___ \          "
echo "         | |     | | | || |_| || || (_) |____) || (_) || |   ____) |         "
echo "         |_|     |_| |_| \__, ||_| \___/|_____/  \___/ |_|  |_____/          "
echo "                         __/ |                                               "
echo "                        |___/                                                "
echo "                                                                             "
echo "           Evolution and Structural impact of Alternative Splicing           "
echo "                                                                             "
echo "                                                                             "
echo " You need to indicate your MODELLER license key to use the homology modelling"
echo " module of PhyloSofS. To do that, you can run the following command replacing"
echo " license_key with your MODELLER license key (https://salilab.org/modeller/): "
echo "                                                                             "
echo " sed -i 's/xxx/license_key/' /usr/lib/modeller9.21/modlib/modeller/config.py "
echo "                                                                             "
